// templates/angular-node/frontend/src/app/app.component.ts
import { NgFor } from "@angular/common";
import { Component } from "@angular/core";

@Component({
  selector: "app-root",
  standalone: true,
  imports: [NgFor],
  template: `
    <main class="studio-shell">
      <header class="studio-hero">
        <p class="studio-kicker">ANGULAR + NODE</p>
        <h1>Structured SPA Delivery Baseline</h1>
        <p>
          A Vercel-inspired starting point for teams shipping Angular frontends
          with Express APIs through a single orchestrated workflow.
        </p>
      </header>

      <section class="workflow-grid" aria-label="Workflow pipeline">
        <article
          *ngFor="let item of workflow"
          class="workflow-step"
          [attr.data-tone]="item.tone"
        >
          <h2>{{ item.title }}</h2>
          <p>{{ item.summary }}</p>
          <code>{{ item.command }}</code>
        </article>
      </section>

      <section class="foundation-grid" aria-label="Project foundations">
        <article *ngFor="let item of foundations" class="foundation-card">
          <h2>{{ item.title }}</h2>
          <p>{{ item.detail }}</p>
          <code>{{ item.anchor }}</code>
        </article>
      </section>

      <section class="command-board" aria-label="Bootstrap commands">
        <h2>Bootstrap Commands</h2>
        <ol>
          <li *ngFor="let step of runbook">
            <code>{{ step }}</code>
          </li>
        </ol>
      </section>

      <footer class="resource-row" aria-label="Documentation links">
        <a
          *ngFor="let resource of resources"
          [href]="resource.href"
          target="_blank"
          rel="noreferrer"
        >
          {{ resource.label }}
        </a>
      </footer>
    </main>
  `,
  styles: [
    `
      :host {
        display: block;
        min-height: 100vh;
        font-family:
          "Geist", "Inter", "Segoe UI", "Helvetica Neue", Arial, sans-serif;
        background:
          radial-gradient(
            circle at 15% -10%,
            rgba(56, 189, 248, 0.2),
            transparent 46%
          ),
          radial-gradient(
            circle at 85% 0%,
            rgba(34, 197, 94, 0.14),
            transparent 42%
          ),
          #050505;
        color: #ededed;
      }

      .studio-shell {
        width: min(1120px, 100%);
        margin: 0 auto;
        padding: clamp(1.25rem, 3vw, 2.75rem) clamp(1rem, 2.5vw, 2rem) 2.5rem;
        display: grid;
        gap: 1rem;
        box-sizing: border-box;
      }

      .studio-hero {
        border-radius: 12px;
        border: 1px solid rgba(255, 255, 255, 0.08);
        background: linear-gradient(
          180deg,
          rgba(11, 11, 13, 0.96),
          rgba(8, 8, 10, 0.95)
        );
        padding: clamp(1.15rem, 2.4vw, 2rem);
        box-shadow:
          rgba(0, 0, 0, 0.5) 0 30px 80px,
          rgba(255, 255, 255, 0.03) 0 1px 0 inset;
      }

      .studio-kicker {
        margin: 0;
        font-family: "Geist Mono", "SFMono-Regular", Menlo, Consolas, monospace;
        font-size: 0.72rem;
        letter-spacing: 0.24em;
        text-transform: uppercase;
        color: #a1a1aa;
      }

      .studio-hero h1 {
        margin: 0.55rem 0 0.75rem;
        font-size: clamp(2rem, 5vw, 3.35rem);
        line-height: 1.02;
        letter-spacing: -0.06em;
        font-weight: 600;
        color: #fafafa;
      }

      .studio-hero p {
        margin: 0;
        max-width: 66ch;
        color: #a1a1aa;
        line-height: 1.65;
      }

      .workflow-grid {
        display: grid;
        gap: 0.9rem;
        grid-template-columns: repeat(3, minmax(0, 1fr));
      }

      .workflow-step {
        border-top: 3px solid #27272a;
        border-right: 1px solid rgba(255, 255, 255, 0.08);
        border-bottom: 1px solid rgba(255, 255, 255, 0.08);
        border-left: 1px solid rgba(255, 255, 255, 0.08);
        border-radius: 10px;
        background: #0b0b0d;
        padding: 1rem;
        box-shadow: rgba(255, 255, 255, 0.03) 0 1px 0 inset;
      }

      .workflow-step[data-tone="develop"] {
        border-top-color: #38bdf8;
      }

      .workflow-step[data-tone="preview"] {
        border-top-color: #a855f7;
      }

      .workflow-step[data-tone="ship"] {
        border-top-color: #22c55e;
      }

      .workflow-step h2 {
        margin: 0;
        font-size: 1.12rem;
        letter-spacing: -0.02em;
        color: #f5f5f5;
      }

      .workflow-step p {
        margin: 0.5rem 0 0.8rem;
        color: #a1a1aa;
      }

      .workflow-step code {
        font-family: "Geist Mono", "SFMono-Regular", Menlo, Consolas, monospace;
        font-size: 0.78rem;
        border-radius: 9999px;
        padding: 0.34rem 0.62rem;
        border: 1px solid rgba(125, 211, 252, 0.3);
        background: rgba(125, 211, 252, 0.12);
        color: #7dd3fc;
      }

      .foundation-grid {
        display: grid;
        grid-template-columns: repeat(2, minmax(0, 1fr));
        gap: 0.9rem;
      }

      .foundation-card {
        border-radius: 10px;
        border: 1px solid rgba(255, 255, 255, 0.08);
        background: #0b0b0d;
        padding: 1rem;
        box-shadow: rgba(255, 255, 255, 0.03) 0 1px 0 inset;
      }

      .foundation-card h2 {
        margin: 0;
        font-size: 1.05rem;
        letter-spacing: -0.02em;
        color: #f5f5f5;
      }

      .foundation-card p {
        margin: 0.5rem 0 0.78rem;
        color: #a1a1aa;
      }

      .foundation-card code,
      .command-board code {
        font-family: "Geist Mono", "SFMono-Regular", Menlo, Consolas, monospace;
        font-size: 0.8rem;
        border: 1px solid rgba(255, 255, 255, 0.1);
        background: rgba(255, 255, 255, 0.04);
        color: #d4d4d8;
        border-radius: 6px;
        padding: 0.28rem 0.46rem;
      }

      .command-board {
        border-radius: 10px;
        border: 1px solid rgba(255, 255, 255, 0.08);
        background: #0b0b0d;
        padding: 1rem;
        box-shadow: rgba(255, 255, 255, 0.03) 0 1px 0 inset;
      }

      .command-board h2 {
        margin: 0 0 0.7rem;
        font-size: 1.06rem;
        letter-spacing: -0.02em;
        color: #f5f5f5;
      }

      .command-board ol {
        margin: 0;
        padding-left: 1.1rem;
        display: grid;
        gap: 0.5rem;
      }

      .resource-row {
        display: flex;
        flex-wrap: wrap;
        gap: 0.65rem;
      }

      .resource-row a {
        text-decoration: none;
        font-size: 0.86rem;
        font-weight: 500;
        color: #e4e4e7;
        border-radius: 6px;
        border: 1px solid rgba(255, 255, 255, 0.08);
        background: #0d0d10;
        padding: 0.42rem 0.74rem;
        transition:
          border-color 180ms ease,
          background-color 180ms ease;
      }

      .resource-row a:hover {
        border-color: rgba(255, 255, 255, 0.2);
        background: #141418;
      }

      @media (max-width: 920px) {
        .workflow-grid {
          grid-template-columns: 1fr;
        }
      }

      @media (max-width: 680px) {
        .foundation-grid {
          grid-template-columns: 1fr;
        }
      }
    `,
  ],
})
export class AppComponent {
  readonly workflow = [
    {
      tone: "develop",
      title: "Develop",
      summary: "Implement Angular UI with fast feedback and API proxy support.",
      command: "npm run dev:frontend",
    },
    {
      tone: "preview",
      title: "Preview",
      summary:
        "Validate Express routes and contracts in isolated backend runtime.",
      command: "npm run dev:server",
    },
    {
      tone: "ship",
      title: "Ship",
      summary:
        "Launch both services from one root command through concurrently.",
      command: "npm run dev",
    },
  ];

  readonly foundations = [
    {
      title: "Frontend Surface",
      detail: "Angular app scaffolding ready for modular UI and route growth.",
      anchor: "frontend/src/app/",
    },
    {
      title: "Backend Core",
      detail:
        "Express service structure with controllers, routes, and utility modules.",
      anchor: "server/src/",
    },
  ];

  readonly runbook = [
    "npm install",
    "npm run setup",
    "cp server/.env.example server/.env",
    "npm run dev",
  ];

  readonly resources = [
    { label: "Angular Docs", href: "https://angular.dev" },
    { label: "Express Docs", href: "https://expressjs.com/" },
    { label: "RxJS Docs", href: "https://rxjs.dev/guide/overview" },
  ];
}

// templates/mern-tw/client/src/App.jsx
function App() {
  const workflow = [
    {
      title: "Develop",
      summary:
        "Build React features with instant HMR and prewired API forwarding.",
      command: "npm run dev:client",
      accent: "border-t-[#0a72ef]",
    },
    {
      title: "Preview",
      summary: "Validate Express routes and payload contracts before release.",
      command: "npm run dev:server",
      accent: "border-t-[#de1d8d]",
    },
    {
      title: "Ship",
      summary: "Run frontend and backend together through one root command.",
      command: "npm run dev",
      accent: "border-t-[#ff5b4f]",
    },
  ];

  const foundations = [
    {
      title: "Client Surface",
      detail:
        "React + Vite workspace with straightforward component and data-flow layering.",
      anchor: "client/src/",
    },
    {
      title: "Server Core",
      detail:
        "Express architecture with routes, controllers, services, and middleware boundaries.",
      anchor: "server/src/",
    },
  ];

  const setupSteps = [
    "npm install",
    "npm run setup",
    "cp server/.env.example server/.env",
    "npm run dev",
  ];

  const resources = [
    { label: "React Docs", href: "https://react.dev/learn" },
    { label: "Express Docs", href: "https://expressjs.com/" },
    { label: "MongoDB Docs", href: "https://www.mongodb.com/docs/" },
  ];

  return (
    <main className="relative min-h-screen overflow-hidden bg-[#050505] text-[#ededed]">
      <div
        aria-hidden="true"
        className="pointer-events-none absolute inset-0 overflow-hidden"
      >
        <div className="absolute -top-36 left-0 h-80 w-80 rounded-full bg-sky-400/20 blur-3xl" />
        <div className="absolute -top-28 right-0 h-72 w-72 rounded-full bg-emerald-400/15 blur-3xl" />
      </div>

      <div className="relative mx-auto grid w-full max-w-6xl gap-4 px-4 py-6 md:px-8 md:py-10">
        <header className="rounded-xl border border-white/10 bg-[#0b0b0d] p-5 shadow-[0_24px_60px_rgba(0,0,0,0.45),inset_0_1px_0_rgba(255,255,255,0.04)] md:p-8">
          <p className="font-mono text-[0.72rem] uppercase tracking-[0.24em] text-[#a1a1aa]">
            MERN STACK + TAILWIND
          </p>
          <h1 className="mt-2 text-[clamp(2rem,5vw,3.35rem)] font-semibold leading-[1.02] tracking-[-0.06em] text-white">
            Deploy-Ready Full-Stack Foundation
          </h1>
          <p className="mt-3 max-w-[66ch] leading-[1.65] text-[#a1a1aa]">
            A utility-first baseline for teams shipping production-grade web
            products with fast iteration loops and explicit boundaries.
          </p>
        </header>

        <section
          className="grid gap-3 md:grid-cols-3"
          aria-label="Workflow pipeline"
        >
          {workflow.map((item) => (
            <article
              key={item.title}
              className={`rounded-[10px] border border-white/10 border-t-[3px] bg-[#0b0b0d] p-4 shadow-[inset_0_1px_0_rgba(255,255,255,0.03)] ${item.accent}`}
            >
              <h2 className="text-[1.12rem] tracking-[-0.02em] text-[#f5f5f5]">
                {item.title}
              </h2>
              <p className="mt-2 mb-3 text-[#a1a1aa]">{item.summary}</p>
              <code className="inline-block rounded-full border border-[#7dd3fc]/30 bg-[#7dd3fc]/10 px-2.5 py-1 font-mono text-xs text-[#7dd3fc]">
                {item.command}
              </code>
            </article>
          ))}
        </section>

        <section
          className="grid gap-3 md:grid-cols-2"
          aria-label="Project foundations"
        >
          {foundations.map((item) => (
            <article
              key={item.title}
              className="rounded-[10px] border border-white/10 bg-[#0b0b0d] p-4 shadow-[inset_0_1px_0_rgba(255,255,255,0.03)]"
            >
              <h2 className="text-[1.05rem] tracking-[-0.02em] text-[#f5f5f5]">
                {item.title}
              </h2>
              <p className="mt-2 mb-3 text-[#a1a1aa]">{item.detail}</p>
              <code className="rounded-md border border-white/10 bg-white/5 px-2 py-1 font-mono text-xs text-[#d4d4d8]">
                {item.anchor}
              </code>
            </article>
          ))}
        </section>

        <section
          className="rounded-[10px] border border-white/10 bg-[#0b0b0d] p-4 shadow-[inset_0_1px_0_rgba(255,255,255,0.03)]"
          aria-label="Bootstrap commands"
        >
          <h2 className="text-[1.06rem] tracking-[-0.02em] text-[#f5f5f5]">
            Bootstrap Commands
          </h2>
          <ol className="mt-3 grid list-decimal gap-2 pl-5">
            {setupSteps.map((step) => (
              <li key={step}>
                <code className="rounded-md border border-white/10 bg-white/5 px-2 py-1 font-mono text-xs text-[#d4d4d8]">
                  {step}
                </code>
              </li>
            ))}
          </ol>
        </section>

        <footer
          className="flex flex-wrap gap-2.5"
          aria-label="Documentation links"
        >
          {resources.map((item) => (
            <a
              key={item.label}
              href={item.href}
              target="_blank"
              rel="noreferrer"
              className="rounded-md border border-white/10 bg-[#0d0d10] px-3 py-1.5 text-sm font-medium text-[#e4e4e7] transition-colors hover:border-white/20 hover:bg-[#141418]"
            >
              {item.label}
            </a>
          ))}
        </footer>
      </div>
    </main>
  );
}

export default App;
